- src: Lowess.ec2
  version: master

- src: Lowess.common
  version: master

- src: Lowess.netdata
  version: master

- src: Lowess.nginx
  version: master

- src: Lowess.uwsgi
  version: master

- src: Lowess.aws_360_api
  version: master
